<?php

namespace Crystal\planillaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * catEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class catEmpresaRepository extends EntityRepository
{
}
