<?php

namespace Crystal\planillaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ctrCalculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ctrCalculoRepository extends EntityRepository
{
}
