<?php

namespace Crystal\planillaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ctrFaltasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ctrFaltasRepository extends EntityRepository
{
}
