
crystalrutas:
    resource: "@CrystalrutasBundle/Resources/config/routing.yml"
    prefix:   /

crystalplanilla:
    resource: "@CrystalplanillaBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
