parameters:
#    crystalplanilla.example.class: Crystal\planillaBundle\Example

services:
#    crystalplanilla.example:
#        class: %crystalplanilla.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
