parameters:
#    crystalrutas.example.class: Crystal\rutasBundle\Example

services:
#    crystalrutas.example:
#        class: %crystalrutas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
